apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "loki-stack.selectorLabels" . | nindent 4 }}
