apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
  selector:
    {{- include "loki-stack.selectorLabels" . | nindent 4 }}
