apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-querier
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    component: querier
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "loki-stack.selectorLabels" . | nindent 6 }}
      component: querier
  template:
    metadata:
      labels:
        {{- include "loki-stack.selectorLabels" . | nindent 8 }}
        component: querier
    spec:
      containers:
        - name: querier
          image: grafana/loki:{{ .Values.loki.image.tag | default "2.9.1" }}
          args:
            - "-target=querier"
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /etc/loki
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: loki-config
